<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /post/view
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: view.php	Friday 10th of December 2021 06:20:54 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1639160454 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_possystem', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1639160454 )
                            foreach( $x_1639160454 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_possystem/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Friday 10th of December 2021 06:20:53 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html>
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script><link rel="stylesheet" type="text/css" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_possystem/main.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
</head>
<body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
        <!-- TODO: Here goes your content! -->
        <div id="page-container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
            
<?php
//pc_body_1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_53dc3d23aa1e349e011a99960f4b904e ) &&  is_object( $_53dc3d23aa1e349e011a99960f4b904e ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_53dc3d23aa1e349e011a99960f4b904e->view(), '' ) : null );

//pc_body_1 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_1 /post/view Begins Here

//pc_body_1 /post/view Ends Here
?>


<?php
//oneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_possystem/template Ends Here
?><?php
//oneness /post/view Begins Here

//oneness /post/view Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_possystem/template Ends Here
?><?php
//middlebar /post/view Begins Here

echo ( ! empty( $_5f9be6ccbb65ef7f547bc302f58e849f ) &&  is_object( $_5f9be6ccbb65ef7f547bc302f58e849f ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_5f9be6ccbb65ef7f547bc302f58e849f->view(), '' ) : null );

//middlebar /post/view Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome1 /post/view Begins Here

echo ( ! empty( $_3a61f077bfdb4a77f7b59607e251822d ) &&  is_object( $_3a61f077bfdb4a77f7b59607e251822d ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_3a61f077bfdb4a77f7b59607e251822d->view(), 'well' ) : null );

echo ( ! empty( $_1e8bd1e6d234c6fc2682d667d2ba9384 ) &&  is_object( $_1e8bd1e6d234c6fc2682d667d2ba9384 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_1e8bd1e6d234c6fc2682d667d2ba9384->view(), '' ) : null );

							if( Ayoola_Page::hasPriviledge( array (
  0 => '98',
  1 => '99',
), array( 'strict' => true ) ) && ! empty( $_09f468859316e6f5cf5fa229c4035263 ) && is_object( $_09f468859316e6f5cf5fa229c4035263 ) )
							{
								echo $_09f468859316e6f5cf5fa229c4035263->view();
							}
							
//twosome1 /post/view Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome2 /post/view Begins Here

echo ( ! empty( $_6fcd9c1619ba5708715b9930263b5399 ) &&  is_object( $_6fcd9c1619ba5708715b9930263b5399 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_6fcd9c1619ba5708715b9930263b5399->view(), '' ) : null );

echo ( ! empty( $_bc665ecf897c5dfc2ba52cb5a2e43fb6 ) &&  is_object( $_bc665ecf897c5dfc2ba52cb5a2e43fb6 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_bc665ecf897c5dfc2ba52cb5a2e43fb6->view(), '' ) : null );

//twosome2 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome1 /post/view Begins Here

//threesome1 /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome2 /post/view Begins Here

//threesome2 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome3 /post/view Begins Here

//threesome3 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome1 /post/view Begins Here

//foursome1 /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome2 /post/view Begins Here

//foursome2 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome3 /post/view Begins Here

//foursome3 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome4 /post/view Begins Here

//foursome4 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbar /post/view Begins Here

//leftbar /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbarright /post/view Begins Here

//leftbarright /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbarleft /post/view Begins Here

echo ( ! empty( $_6a6e9195af68d2bc89b66a987cd65894 ) &&  is_object( $_6a6e9195af68d2bc89b66a987cd65894 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_6a6e9195af68d2bc89b66a987cd65894->view(), '' ) : null );

//rightbarleft /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbar /post/view Begins Here

//rightbar /post/view Ends Here
?>
											</div>   
										</div> 
									</div> 
								</section><?php
//lastoneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_possystem/template Ends Here
?><?php
//lastoneness /post/view Begins Here

echo ( ! empty( $_4842352f247d06425e3b93ae0e2e2bff ) &&  is_object( $_4842352f247d06425e3b93ae0e2e2bff ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_4842352f247d06425e3b93ae0e2e2bff->view(), '' ) : null );

echo ( ! empty( $_388418e22b4ef88145152b88bf50a461 ) &&  is_object( $_388418e22b4ef88145152b88bf50a461 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_388418e22b4ef88145152b88bf50a461->view(), '' ) : null );

echo ( ! empty( $_e8d20b82f6c4eb884a809bee7b84e158 ) &&  is_object( $_e8d20b82f6c4eb884a809bee7b84e158 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_e8d20b82f6c4eb884a809bee7b84e158->view(), '' ) : null );

echo ( ! empty( $_c1587c588cc88702179a96345f7e5878 ) &&  is_object( $_c1587c588cc88702179a96345f7e5878 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_c1587c588cc88702179a96345f7e5878->view(), 'well' ) : null );

echo ( ! empty( $_7b29fbca1b27f9b673425476e9fdeb11 ) &&  is_object( $_7b29fbca1b27f9b673425476e9fdeb11 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_7b29fbca1b27f9b673425476e9fdeb11->view(), 'white-well' ) : null );

//lastoneness /post/view Ends Here
?>

            
<?php
//pc_body_2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_dc450638350b1b93ed3c97db6686a474 ) &&  is_object( $_dc450638350b1b93ed3c97db6686a474 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_dc450638350b1b93ed3c97db6686a474->view(), '' ) : null );

//pc_body_2 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_2 /post/view Begins Here

//pc_body_2 /post/view Ends Here
?>



</div>
	<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?>
<?php
//pc_section_after_js /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_section_after_js /post/view Begins Here

//pc_section_after_js /post/view Ends Here
?>

</body>
</html>
