<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /account
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: account.php	Monday 10th of January 2022 12:09:51 PM	ayoola.falola@yahoo.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1641816591 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_possystem', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1641816591 )
                            foreach( $x_1641816591 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_possystem/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Monday 10th of January 2022 12:09:45 PM	ayoola.falola@yahoo.com $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html>
	<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> 
        <link rel="stylesheet" type="text/css" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_possystem/main.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
	</head>
	<body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
        <!-- TODO: Here goes your content! -->
        <div id="page-container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
            <?php
//pc_body_2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_dc450638350b1b93ed3c97db6686a474 ) &&  is_object( $_dc450638350b1b93ed3c97db6686a474 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_dc450638350b1b93ed3c97db6686a474->view(), '' ) : null );

//pc_body_2 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_2 /account Begins Here

//pc_body_2 /account Ends Here
?><?php
//oneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_possystem/template Ends Here
?><?php
//oneness /account Begins Here

//oneness /account Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_possystem/template Ends Here
?><?php
//middlebar /account Begins Here

echo ( ! empty( $_88699203ec4dd2d87090cf3906cfa51f ) &&  is_object( $_88699203ec4dd2d87090cf3906cfa51f ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_88699203ec4dd2d87090cf3906cfa51f->view(), '' ) : null );

//middlebar /account Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome1 /account Begins Here

//twosome1 /account Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome2 /account Begins Here

//twosome2 /account Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome1 /account Begins Here

//threesome1 /account Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome2 /account Begins Here

//threesome2 /account Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome3 /account Begins Here

//threesome3 /account Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome1 /account Begins Here

//foursome1 /account Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome2 /account Begins Here

//foursome2 /account Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome3 /account Begins Here

//foursome3 /account Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome4 /account Begins Here

//foursome4 /account Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbar /account Begins Here

//leftbar /account Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbarright /account Begins Here

//leftbarright /account Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbarleft /account Begins Here

echo ( ! empty( $_0ea76fee692fbace3486aa38ccce2a27 ) &&  is_object( $_0ea76fee692fbace3486aa38ccce2a27 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_0ea76fee692fbace3486aa38ccce2a27->view(), '' ) : null );

//rightbarleft /account Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbar /account Begins Here

echo ( ! empty( $_cc5ff4e9ddf47660674d16730125c401 ) &&  is_object( $_cc5ff4e9ddf47660674d16730125c401 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_cc5ff4e9ddf47660674d16730125c401->view(), 'dark' ) : null );

echo ( ! empty( $_efc8f9eb55ba74ed03c05e7ca821e6f9 ) &&  is_object( $_efc8f9eb55ba74ed03c05e7ca821e6f9 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_efc8f9eb55ba74ed03c05e7ca821e6f9->view(), '' ) : null );

//rightbar /account Ends Here
?>
											</div>   
										</div> 
									</div> 
									</section><?php
//lastoneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_possystem/template Ends Here
?><?php
//lastoneness /account Begins Here

//lastoneness /account Ends Here
?>

            <?php
//pc_body_3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_87f0237f9baf04444d8ba7c60f39cf29 ) &&  is_object( $_87f0237f9baf04444d8ba7c60f39cf29 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_87f0237f9baf04444d8ba7c60f39cf29->view(), '' ) : null );

//pc_body_3 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_3 /account Begins Here

//pc_body_3 /account Ends Here
?>

          </div>
	<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?><?php
//pc_section_after_js /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_section_after_js /account Begins Here

//pc_section_after_js /account Ends Here
?>
</body>
</html>
