<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /account/signin
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: signin.php	Monday 10th of January 2022 12:09:50 PM	ayoola.falola@yahoo.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1641816590 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_possystem', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1641816590 )
                            foreach( $x_1641816590 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_possystem/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Monday 10th of January 2022 12:09:45 PM	ayoola.falola@yahoo.com $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html>
	<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> 
        <link rel="stylesheet" type="text/css" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_possystem/main.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
	</head>
	<body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
        <!-- TODO: Here goes your content! -->
        <div id="page-container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
            <?php
//pc_body_2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_dc450638350b1b93ed3c97db6686a474 ) &&  is_object( $_dc450638350b1b93ed3c97db6686a474 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_dc450638350b1b93ed3c97db6686a474->view(), '' ) : null );

//pc_body_2 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_2 /account/signin Begins Here

//pc_body_2 /account/signin Ends Here
?><?php
//oneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_possystem/template Ends Here
?><?php
//oneness /account/signin Begins Here

//oneness /account/signin Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_possystem/template Ends Here
?><?php
//middlebar /account/signin Begins Here

echo ( ! empty( $_abef812fd29cef55d9181f865b477573 ) &&  is_object( $_abef812fd29cef55d9181f865b477573 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_abef812fd29cef55d9181f865b477573->view(), '' ) : null );

//middlebar /account/signin Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome1 /account/signin Begins Here

//twosome1 /account/signin Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//twosome2 /account/signin Begins Here

//twosome2 /account/signin Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome1 /account/signin Begins Here

echo ( ! empty( $_86d2d889f699fa5165c1674f43a7a233 ) &&  is_object( $_86d2d889f699fa5165c1674f43a7a233 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_86d2d889f699fa5165c1674f43a7a233->view(), '' ) : null );

//threesome1 /account/signin Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome2 /account/signin Begins Here

echo ( ! empty( $_40ad3832025d0854a3b6f0a5d136db1d ) &&  is_object( $_40ad3832025d0854a3b6f0a5d136db1d ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_40ad3832025d0854a3b6f0a5d136db1d->view(), '' ) : null );

echo ( ! empty( $_bcfba266637a37366c671ad83f3d8d9a ) &&  is_object( $_bcfba266637a37366c671ad83f3d8d9a ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_bcfba266637a37366c671ad83f3d8d9a->view(), 'well' ) : null );

//threesome2 /account/signin Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//threesome3 /account/signin Begins Here

echo ( ! empty( $_bebd47b76e364a2775d551a8adcb1b20 ) &&  is_object( $_bebd47b76e364a2775d551a8adcb1b20 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_bebd47b76e364a2775d551a8adcb1b20->view(), '' ) : null );

//threesome3 /account/signin Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome1 /account/signin Begins Here

//foursome1 /account/signin Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome2 /account/signin Begins Here

//foursome2 /account/signin Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome3 /account/signin Begins Here

//foursome3 /account/signin Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_possystem/template Ends Here
?><?php
//foursome4 /account/signin Begins Here

//foursome4 /account/signin Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbar /account/signin Begins Here

//leftbar /account/signin Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_possystem/template Ends Here
?><?php
//leftbarright /account/signin Begins Here

//leftbarright /account/signin Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbarleft /account/signin Begins Here

//rightbarleft /account/signin Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_possystem/template Ends Here
?><?php
//rightbar /account/signin Begins Here

//rightbar /account/signin Ends Here
?>
											</div>   
										</div> 
									</div> 
									</section><?php
//lastoneness /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_possystem/template Ends Here
?><?php
//lastoneness /account/signin Begins Here

//lastoneness /account/signin Ends Here
?>

            <?php
//pc_body_3 /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_body_3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_87f0237f9baf04444d8ba7c60f39cf29 ) &&  is_object( $_87f0237f9baf04444d8ba7c60f39cf29 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_87f0237f9baf04444d8ba7c60f39cf29->view(), '' ) : null );

//pc_body_3 /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_body_3 /account/signin Begins Here

//pc_body_3 /account/signin Ends Here
?>

          </div>
	<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?><?php
//pc_section_after_js /layout/pc_layout_possystem/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_possystem/template Ends Here
?><?php
//pc_section_after_js /account/signin Begins Here

//pc_section_after_js /account/signin Ends Here
?>
</body>
</html>
